# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: cvugrinec/pokerhost-service
  tag: latest
  pullSecret: regsecret
  pullPolicy: Always
  # for local development against Minikube registry
  #pullPolicy: Never    
service:
  name: poker-service
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - hello.apimdemo.service.local
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
